name: Build app

on:
  push:
    branches:
      - main
      - pipeline

jobs:
  make-release:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.release_version.outputs.version }}
    steps:
      - name: Copy data
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 20

      - name: Install dependencies
        if:  ${{ github.ref }} == 'refs/heads/main'
        run: yarn add @semantic-release/git @semantic-release/github
      
      - name: Semantic Release
        if:  ${{ github.ref }} == 'refs/heads/main'
        run: npx semantic-release
        env:
          GH_TOKEN : ${{ secrets.GH_TOKEN }}
      
      - id: release_version
        run: |
          echo "version=$(cat ./package.json | jq -r '.version')" >> $GITHUB_OUTPUT

  build-package:
    runs-on: windows-latest
    needs: make-release
    steps:
      - name: Copy data
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      - name: Update package.json with latest version
        run: |
          $VERSION = "${{ needs.make-release.outputs.VERSION }}"
          jq --arg ver "$VERSION" '.version = $ver' package.json > temp.json && mv temp.json package.json

      - name: Install Rust 
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: npm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename app
        run: |
          mkdir .\src-tauri\target\release\bundle\msi\pkg
          mv ".\src-tauri\target\release\bundle\msi\Gerenciador de Atividades - Topocart_${{ needs.make-release.outputs.VERSION }}_x64_en-US.msi" ./src-tauri/target/release/bundle/msi/pkg/gerenciador-atividades.msi

      - uses: shallwefootball/s3-upload-action@master
        name: Upload app to S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: "topocart"
          destination_dir: 'gerenciador-de-atividades'
          source_dir: '.\src-tauri\target\release\bundle\msi\pkg'
      
      - name: Upload app with version tag to FTP
        uses: tomasbkk/action-ftp-upload@v1.0
        with:
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          host: ${{ secrets.FTP_HOST }}
          src: ./src-tauri/target/release/bundle/msi/pkg/gerenciador-atividades.msi
          dest: /home/apontador-horas/apontador-horas-v${{ needs.make-release.outputs.VERSION }}.msi
      
      - name: Upload app with latest tag to FTP
        uses: tomasbkk/action-ftp-upload@v1.0
        with:
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          host: ${{ secrets.FTP_HOST }}
          src: ./src-tauri/target/release/bundle/msi/pkg/gerenciador-atividades.msi
          dest: /home/apontador-horas/apontador-horas-latest.msi
  