name: Build app

on:
  push:
    branches:
      - pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Tauri CLI
      run: |
        npm install -g tauri
        tauri info

    - name: Install dependencies
      run: |
        npm install

    - name: Build the Tauri application for Windows
      run: |
        tauri build --target windows
