name: Versioning and Build

on:
  push:
    branches:
      - develop
      - technical/ci-enhancements

jobs:
  build:
    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest
    
    steps:

      - name: Copy data
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5

      - name: Install dependencies
        run: yarn add semantic-release @semantic-release/git @semantic-release/github @semantic-release/exec json child_process

      - name: Semantic Release
        run: npx semantic-release --dry-run
        env:
          GH_TOKEN : ${{ secrets.GH_TOKEN }}