name: Versioning and Build

on:
  push:
    branches:
      - develop
      - ci-enhancements

jobs:
  build:
    permissions:
      contents: write
      issues: write
      pull-requests: write

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Copy data
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5

      - name: Install dependencies
        run: yarn add semantic-release @semantic-release/git @semantic-release/github json child_process

      - name: Semantic Release
        run: npx semantic-release
        env:
          GH_TOKEN : ${{ secrets.GH_TOKEN }}

      - name: Update tauri.conf.json version
        run: node ./update-tauri-version.js
        
      - name: Install build dependencies
        run: yarn 

      - name: Build Tauri
        if: matrix.os == 'ubuntu-latest'
        run: yarn tauri build

      - name: Build Tauri
        if: matrix.os == 'windows-latest'
        run: yarn tauri build